/**
 * Fonte única de títulos de página, consumida pelo MobileBackHeader.
 * Chave = segmento da rota (case-insensitive). Páginas sem entrada não
 * exibem título no header mobile.
 */
const PAGE_TITLES = {
  AcompanhamentoCarga: "Acompanhamento de Aplicação",
  ControleExecucaoServicos: "Controle de Execução de Serviços",
  RelatorioControleExecucaoServicos: "Controle de Execução de Serviços",
  AcompanhamentoUsinagem: "Acompanhamento de Usinagem",
  BoletimSondagem: "Boletim de Sondagem",
  BoletimSondagemTrado: "Boletim de Sondagem a Trado",
  CertificacaoUsina: "Certificação de Usina",
  ChecklistAplicacao: "Checklist de Aplicação",
  ChecklistConcretagem: "Checklist de Concretagem",
  ChecklistMRAF: "Checklist MRAF",
  ChecklistReciclagem: "Checklist de Reciclagem",
  ChecklistTerraplanagem: "Checklist de Terraplanagem",
  ChecklistUsina: "Checklist de Usina",
  ControleLaboratoristas: "Controle de Laboratoristas",
  Dashboard: "Dashboard",
  DiarioObra: "Diário de Obra",
  EditarNC: "Editar NC",
  EnsaioCAUQ: "Ensaio CAUQ",
  EnsaioDensidade: "Ensaio de Densidade",
  EnsaioDensidadeInSitu: "Densidade In Situ",
  EnsaioGranulometriaIndividual: "Granulometria Individual",
  EnsaioManchaPendulo: "Macrotextura e Microtextura",
  EnsaioMRAF: "Ensaio MRAF",
  EnsaioProctor: "Ensaio Proctor",
  EnsaioRompimentoConcreto: "Rompimento de Concreto",
  EnsaioSondagem: "Ensaio de Sondagem",
  EnsaioTaxaInsumos: "Taxa de Insumos",
  EnsaioTaxaMRAF: "Taxa MRAF",
  EnsaioTaxaPinturaImprimacao: "Taxa de Pintura e Imprimação",
  EnsaioVigaBenkelman: "Viga Benkelman",
  FaixasGranulometricas: "Faixas Granulométricas",
  GestaoNC: "Gestão de NCs",
  GranuMistura: "Granulometria da Mistura",
  Home: "Início",
  "historico-auditoria": "Trilha de Auditoria",
  HistoricoAuditoria: "Trilha de Auditoria",
  ImpressionEtiquetas: "Impressão de Etiquetas",
  MeusEnsaios: "Ensaios Realizados",
  MigracaoDados: "Migração de Dados",
  MonitorProdutividade: "Monitor de Produtividade",
  NaoConformidades: "Não Conformidades",
  NovaNC: "Nova NC",
  Produtividade: "Produtividade",
  Projects: "Projetos",
  Regionais: "Regionais",
  RelatorioAcompanhamentoCarga: "Relatório de Acompanhamento de Aplicação",
  RelatorioAcompanhamentoUsinagem: "Relatório de Acompanhamento de Usinagem",
  RelatorioBoletimSondagem: "Relatório de Boletim de Sondagem",
  RelatorioBoletimSondagemTrado: "Relatório de Boletim de Sondagem a Trado",
  RelatorioCAUQ: "Relatório CAUQ",
  RelatorioCertificacaoUsina: "Relatório de Certificação de Usina",
  RelatorioChecklist: "Relatório de Checklist",
  RelatorioChecklistAplicacao: "Relatório de Checklist de Aplicação",
  RelatorioChecklistConcretagem: "Relatório de Checklist de Concretagem",
  RelatorioChecklistMRAF: "Relatório de Checklist MRAF",
  RelatorioChecklistPage: "Relatório de Checklist",
  RelatorioChecklistReciclagem: "Relatório de Checklist de Reciclagem",
  RelatorioChecklistTerraplanagem: "Relatório de Checklist de Terraplanagem",
  RelatorioControleExecucaoServicos: "Relatório de Controle de Execução",
  RelatorioDensidadeInSitu: "Relatório de Densidade In Situ",
  RelatorioDiario: "Relatório Diário",
  RelatorioEnsaio: "Relatório de Ensaio",
  RelatorioGranuMistura: "Relatório de Granulometria da Mistura",
  RelatorioGranulometriaIndividual: "Relatório de Granulometria Individual",
  RelatorioManchaPendulo: "Relatório de Macrotextura e Microtextura",
  RelatorioNC: "Relatório de NC",
  RelatorioProctor: "Relatório Proctor",
  RelatorioRompimentoConcreto: "Relatório de Rompimento de Concreto",
  RelatorioSondagem: "Relatório de Sondagem",
  RelatorioTaxaInsumos: "Relatório de Taxa de Insumos",
  RelatorioTaxaMRAF: "Relatório de Taxa MRAF",
  RelatorioTaxaPinturaImprimacao: "Relatório de Taxa de Pintura e Imprimação",
  RelatorioUnificado: "Relatório Unificado",
  RelatorioVigaBenkelman: "Relatório de Viga Benkelman",
  RelatoriosUnificados: "Relatórios Unificados",
  ReportarErro: "Reportar Erro",
  ResumosPersonalizados: "Resumos Personalizados",
  Settings: "Configurações",
  SolicitacoesTransferencia: "Solicitações de Transferência",
  Users: "Usuários",
};

const LOOKUP = Object.fromEntries(
  Object.entries(PAGE_TITLES).map(([k, v]) => [k.toLowerCase(), v])
);

export function getPageTitle(pathname) {
  const segment = (pathname || "").split("/")[1] || "";
  return LOOKUP[segment.toLowerCase()] || null;
}