export const TIPOS_ENSAIO = [
  { value: "EnsaioCAUQ", label: "Ensaio CAUQ" },
  { value: "EnsaioSondagem", label: "Sondagem" },
  { value: "EnsaioDensidadeInSitu", label: "Densidade In Situ" },
  { value: "EnsaioTaxaPinturaImprimacao", label: "Taxa de Pintura/Imprimação" },
  { value: "EnsaioManchaPendulo", label: "Mancha + Pêndulo" },
  { value: "ChecklistUsina", label: "Checklist de Usina" },
  { value: "ChecklistAplicacao", label: "Checklist de Aplicação" },
  { value: "ChecklistMRAF", label: "Checklist MRAF" },
  { value: "ChecklistConcretagem", label: "Checklist de Concretagem" },
  { value: "ChecklistTerraplanagem", label: "Checklist de Terraplanagem" },
  { value: "ChecklistReciclagem", label: "Checklist de Reciclagem" },
  { value: "DiarioObra", label: "Diário de Obra" },
  { value: "EnsaioMRAF", label: "Ensaio de MRAF" }
];

export const CAMPOS_POR_TIPO = {
  EnsaioCAUQ: [
    { key: "data_ensaio", label: "Data" },
    { key: "laboratorista_name", label: "Laboratorista" },
    { key: "rodovia", label: "Rodovia" },
    { key: "usina_fornecedora", label: "Usina" },
    { key: "project_name", label: "Projeto" },
    { key: "extracao_ligante.teor_ligante", label: "Teor Ligante (%)" },
    { key: "extracao_ligante.teor_ligante_real", label: "Teor Ligante Real (%)" },
    { key: "granulometria", label: "Granulometria (% passante)", subfields: [
      { key: "peneira_75_0mm", label: 'Nº 3"', astm: 'Nº 3"' },
      { key: "peneira_63_0mm", label: 'Nº 2½"', astm: 'Nº 2½"' },
      { key: "peneira_50_0mm", label: 'Nº 2"', astm: 'Nº 2"' },
      { key: "peneira_37_5mm", label: 'Nº 1½"', astm: 'Nº 1½"' },
      { key: "peneira_25_0mm", label: 'Nº 1"', astm: 'Nº 1"' },
      { key: "peneira_19_0mm", label: 'Nº ¾"', astm: 'Nº ¾"' },
      { key: "peneira_16_0mm", label: 'Nº ⅝"', astm: 'Nº ⅝"' },
      { key: "peneira_12_5mm", label: 'Nº ½"', astm: 'Nº ½"' },
      { key: "peneira_9_5mm", label: 'Nº ⅜"', astm: 'Nº ⅜"' },
      { key: "peneira_4_75mm", label: "Nº 4", astm: "Nº 4" },
      { key: "peneira_2_36mm", label: "Nº 8", astm: "Nº 8" },
      { key: "peneira_2_0mm", label: "Nº 10", astm: "Nº 10" },
      { key: "peneira_1_18mm", label: "Nº 16", astm: "Nº 16" },
      { key: "peneira_0_6mm", label: "Nº 30", astm: "Nº 30" },
      { key: "peneira_0_42mm", label: "Nº 40", astm: "Nº 40" },
      { key: "peneira_0_3mm", label: "Nº 50", astm: "Nº 50" },
      { key: "peneira_0_18mm", label: "Nº 80", astm: "Nº 80" },
      { key: "peneira_0_15mm", label: "Nº 100", astm: "Nº 100" },
      { key: "peneira_0_075mm", label: "Nº 200", astm: "Nº 200" }
    ]},
    { key: "corpos_prova_marshall", label: "Parâmetros Marshall", subfields: [
      { key: "densidade_aparente", label: "Densidade Aparente (g/cm³)" },
      { key: "volume_vazios", label: "Volume Vazios (%)" },
      { key: "vam", label: "VAM (%)" },
      { key: "rbv", label: "RBV (%)" },
      { key: "rtcd_valor", label: "RTCD (MPa)" },
      { key: "estabilidade_corrigida", label: "Estabilidade (Kgf/cm²)" },
      { key: "fluencia", label: "Fluência (mm)" }
    ]},
    { key: "densidade_rice.densidade_rice", label: "RICE - Densidade (g/cm³)" },
    { key: "approved", label: "Status Aprovação" }
  ],
  EnsaioSondagem: [
    { key: "data", label: "Data Ensaio" },
    { key: "project_name", label: "Projeto" },
    { key: "usina_fornecedora", label: "Usina" },
    { key: "dens_aparente_projeto", label: "Dens. Aparente Projeto (g/cm³)" },
    { key: "corpos_prova", label: "Corpos de Prova", subfields: [
      { key: "data_execucao", label: "Data Execução CP" },
      { key: "estaca", label: "Estaca" },
      { key: "lado", label: "Lado" },
      { key: "media_espessura", label: "Espessura Média (cm)" },
      { key: "densidade", label: "Dens. Aparente CP (g/cm³)" },
      { key: "dens_rice_do_dia", label: "Dens. RICE do Dia (g/cm³)" },
      { key: "gc_dens_projeto", label: "GC Dens. Projeto (%)" },
      { key: "gc_dens_rice_dia", label: "GC RICE do Dia (%)" },
      { key: "rtcd_25c", label: "RTCD (MPa)" }
    ]},
    { key: "approved", label: "Status Aprovação" }
  ],
  EnsaioDensidadeInSitu: [
    { key: "data_ensaio", label: "Data" },
    { key: "camada", label: "Camada" },
    { key: "material", label: "Material" },
    { key: "furos", label: "Dados do Furo", subfields: [
      { key: "estaca", label: "Estaca" },
      { key: "densidade_seca_solo", label: "Densidade Seca Solo (g/cm³)" },
      { key: "umidade", label: "Umidade (%)" }
    ]},
    { key: "dados_proctor.densidade_seca_max", label: "Densidade Seca Max Proctor (g/cm³)" },
    { key: "dados_proctor.umidade_otima", label: "Umidade Ótima Proctor (%)" },
    { key: "furos_variacao", label: "Dados do Furo Final", subfields: [
      { key: "desvio_umidade", label: "Variação Umidade (%)" },
      { key: "grau_compactacao", label: "Grau Compactação (%)" }
    ]}
  ],
  EnsaioTaxaPinturaImprimacao: [
    { key: "data_ensaio", label: "Data" },
    { key: "tipo_servico", label: "Serviço" },
    { key: "ensaios", label: "Dados do Ensaio", subfields: [
      { key: "camada", label: "Camada" },
      { key: "material_camada", label: "Material" },
      { key: "estaca", label: "Estaca" },
      { key: "taxa_aplicada", label: "Taxa Aplicada (l/m²)" },
      { key: "taxa_residual", label: "Taxa Residual (l/m²)" },
      { key: "taxa_emulsao_aplicada", label: "Taxa Emulsão (l/m²)" },
      { key: "ensaio_residuo.data", label: "Data Ensaio Resíduo" },
      { key: "ensaio_residuo.residuo", label: "% Resíduo" }
    ]}
  ],
  EnsaioManchaPendulo: [
    { key: "laboratorista_name", label: "Laboratorista" },
    { key: "rodovia", label: "Rodovia" },
    { key: "trecho", label: "Trecho" },
    { key: "empreiteira", label: "Empreiteira" },
    { key: "camada", label: "Camada" },
    { key: "pista", label: "Pista" },
    { key: "orgao", label: "Orgão" },
    { key: "data_ensaio", label: "Data Ensaio" },
    { key: "data_aplicacao", label: "Data Aplicação" },
    { key: "media_hs", label: "Média HS (mm)" },
    { key: "classificacao_media_hs", label: "Classificação HS" },
    { key: "media_vrd", label: "Média VRD" },
    { key: "classificacao_media_vrd", label: "Classificação VRD" },
    { key: "condicao_conformidade", label: "Conformidade" }
  ],
  ChecklistUsina: [
    { key: "laboratorista_name", label: "Laboratorista" },
    { key: "project_name", label: "Projeto" },
    { key: "faixa_especificada", label: "Faixa" },
    { key: "ligante", label: "Ligante" },
    { key: "pedreira", label: "Pedreira" },
    { key: "usina", label: "Usina" },
    { key: "fornecedora_ligante", label: "Fornecedora Ligante" },
    { key: "equivalente_areia_resultados", label: "Equiv. Areia", subfields: [
      { key: "resultado_1", label: "Equiv. Areia 1 (%)" },
      { key: "resultado_2", label: "Equiv. Areia 2 (%)" },
      { key: "resultado_3", label: "Equiv. Areia 3 (%)" }
    ]},
    { key: "controle_ligante.nota_fiscal", label: "Ligante - NF" },
    { key: "controle_ligante.fornecedor", label: "Ligante - Fornecedor" },
    { key: "controle_ligante.placa_carreta", label: "Ligante - Placa" },
    { key: "controle_ligante.quantidade_toneladas", label: "Ligante - Qtd (t)" },
    { key: "controle_ligante.viscosidade_1_resultado", label: "Ligante - Visc. 1 (cP)" },
    { key: "controle_ligante.viscosidade_1_conforme", label: "Ligante - Visc. 1 Conforme" },
    { key: "controle_ligante.viscosidade_2_resultado", label: "Ligante - Visc. 2 (cP)" },
    { key: "controle_ligante.viscosidade_2_conforme", label: "Ligante - Visc. 2 Conforme" },
    { key: "controle_ligante.viscosidade_3_resultado", label: "Ligante - Visc. 3 (cP)" },
    { key: "controle_ligante.viscosidade_3_conforme", label: "Ligante - Visc. 3 Conforme" },
    { key: "controle_ligante.recuperacao_elastica_resultado", label: "Ligante - Recup. Elástica (%)" },
    { key: "controle_ligante.recuperacao_elastica_conforme", label: "Ligante - Recup. Elástica Conforme" },
    { key: "controle_ligante.penetracao_resultado", label: "Ligante - Penetração (0,1mm)" },
    { key: "controle_ligante.penetracao_conforme", label: "Ligante - Penetração Conforme" },
    { key: "controle_ligante.ponto_amolecimento_resultado", label: "Ligante - Pto. Amolec. (°C)" },
    { key: "controle_ligante.ponto_amolecimento_conforme", label: "Ligante - Pto. Amolec. Conforme" },
    { key: "controle_ligante.ponto_fulgor_resultado", label: "Ligante - Pto. Fulgor (°C)" },
    { key: "controle_ligante.ponto_fulgor_conforme", label: "Ligante - Pto. Fulgor Conforme" },
    { key: "rodadas_producao", label: "Rodadas Produção", subfields: [
      { key: "quantidade_produzida", label: "Qtd. Produzida (t)" }
    ]},
    { key: "controle_cauq", label: "Controle CAUQ", subfields: [
      { key: "teor_ligante.rotarex_1", label: "Teor Ligante Rotarex 1 (%)" },
      { key: "teor_ligante.rotarex_2", label: "Teor Ligante Rotarex 2 (%)" },
      { key: "teor_ligante.rotarex_3", label: "Teor Ligante Rotarex 3 (%)" },
      { key: "teor_ligante.soxhlet_1", label: "Teor Ligante Soxhlet 1 (%)" },
      { key: "teor_ligante.soxhlet_2", label: "Teor Ligante Soxhlet 2 (%)" },
      { key: "teor_ligante.soxhlet_3", label: "Teor Ligante Soxhlet 3 (%)" },
      { key: "teor_ligante.quantidade", label: "Qtd. Teor Ligante" },
      { key: "teor_ligante.conforme", label: "Teor Ligante Conforme" },
      { key: "densidade_aparente.resultados", label: "Densidade Aparente (g/cm³)" },
      { key: "densidade_aparente.quantidade", label: "Qtd. Densidade Aparente" },
      { key: "densidade_rice.resultados", label: "Densidade RICE (g/cm³)" },
      { key: "densidade_rice.quantidade", label: "Qtd. Densidade RICE" },
      { key: "volume_vazios.resultados", label: "Volume Vazios (%)" },
      { key: "volume_vazios.quantidade", label: "Qtd. Volume Vazios" },
      { key: "volume_vazios.conforme", label: "Volume Vazios Conforme" },
      { key: "rbv.resultados", label: "RBV (%)" },
      { key: "rbv.quantidade", label: "Qtd. RBV" },
      { key: "rbv.conforme", label: "RBV Conforme" },
      { key: "estabilidade.resultados", label: "Estabilidade (Kgf)" },
      { key: "estabilidade.quantidade", label: "Qtd. Estabilidade" },
      { key: "estabilidade.conforme", label: "Estabilidade Conforme" },
      { key: "fluencia.resultados", label: "Fluência (mm)" },
      { key: "fluencia.quantidade", label: "Qtd. Fluência" },
      { key: "fluencia.conforme", label: "Fluência Conforme" },
      { key: "rtcd_25c.resultados", label: "RTCD (MPa)" },
      { key: "rtcd_25c.quantidade", label: "Qtd. RTCD" },
      { key: "rtcd_25c.conforme", label: "RTCD Conforme" }
    ]},
    { key: "acoes_corretivas_realizado", label: "Ações Corretivas" }
  ],
  ChecklistAplicacao: [
    { key: "laboratorista_name", label: "Laboratorista" },
    { key: "rodovia", label: "Rodovia" },
    { key: "trecho", label: "Trecho" },
    { key: "usina", label: "Usina" },
    { key: "fresagem_preparacao.superficie_limpa", label: "Superfície Limpa Após Fresagem" },
    { key: "fresagem_preparacao.destinacao_material_fresado", label: "Destinação Material Fresado" },
    { key: "fresagem_preparacao.material_solto_removido", label: "Remoção Material Solto" },
    { key: "fresagem_preparacao.pavimento_pronto_pintura", label: "Pavimento em Condições para Pintura" },
    { key: "pintura_ligacao.pintura_barra_espargidora.realizado", label: "Pintura Barra Espargidora" },
    { key: "pintura_ligacao.tempo_rompimento_cura.realizado", label: "Tempo Rompimento/Cura" },
    { key: "pintura_ligacao.taxa_pintura.resultado", label: "Taxa de Pintura (l/m²)" },
    { key: "pintura_ligacao.taxa_pintura.conforme", label: "Taxa de Pintura Conforme" },
    { key: "pintura_ligacao.residuo_emulsao.resultado", label: "Resíduo da Emulsão (%)" },
    { key: "pintura_ligacao.taxa_pintura_residual.resultado", label: "Taxa de Pintura Residual (l/m²)" },
    { key: "pintura_ligacao.taxa_pintura_residual.conforme", label: "Taxa de Pintura Residual Conforme" },
    { key: "controle_aplicacao.temp_aplicacao_cargas.quantidade", label: "Temp. Aplicação Qtd" },
    { key: "controle_aplicacao.temp_aplicacao_cargas.conforme", label: "Temp. Aplicação Conforme" },
    { key: "controle_aplicacao.espessura_camada.quantidade", label: "Espessura Camada Qtd" },
    { key: "controle_aplicacao.espessura_camada.conforme", label: "Espessura Camada Conforme" },
    { key: "acoes_corretivas_realizado", label: "Ações Corretivas" }
  ],
  ChecklistMRAF: [
    { key: "laboratorista_name", label: "Laboratorista" },
    { key: "rodovia", label: "Rodovia" },
    { key: "trecho", label: "Trecho" },
    { key: "project_name", label: "Projeto" },
    { key: "empreiteira", label: "Empreiteira" },
    { key: "condicionamento_insumos.agregados_separados", label: "Agregados Separados" },
    { key: "condicionamento_insumos.agregados_cobertos", label: "Agregados Cobertos" },
    { key: "condicionamento_insumos.filler_utilizado", label: "Filler Utilizado" },
    { key: "condicionamento_insumos.utilizacao_aditivos", label: "Utilização de Aditivos" },
    { key: "condicionamento_insumos.agua_contaminada", label: "Água Contaminada" },
    { key: "preparacao_superficie.superficie_umida", label: "Superfície Úmida" },
    { key: "preparacao_superficie.temperatura_pavimento", label: "Temp. Pavimento (°C)" },
    { key: "preparacao_superficie.pavimento_patologias", label: "Pavimento com Patologias" },
    { key: "preparacao_superficie.superficie_fresada", label: "Superfície Fresada" },
    { key: "preparacao_superficie.superficie_limpa", label: "Superfície Limpa" },
    { key: "acompanhamento_aplicacao.tempo_rompimento_cura.realizado", label: "Tempo Rompimento/Cura" },
    { key: "acompanhamento_aplicacao.taxa_aplicacao.realizado", label: "Taxa Aplicação Realizado" },
    { key: "acompanhamento_aplicacao.taxa_aplicacao.resultado", label: "Taxa Aplicação (kg/m²)" },
    { key: "acompanhamento_aplicacao.taxa_aplicacao.conforme", label: "Taxa Aplicação Conforme" },
    { key: "acompanhamento_aplicacao.residuo_emulsao.realizado", label: "Resíduo Emulsão Realizado" },
    { key: "acompanhamento_aplicacao.residuo_emulsao.resultado", label: "Resíduo Emulsão (%)" },
    { key: "acompanhamento_aplicacao.residuo_emulsao.conforme", label: "Resíduo Emulsão Conforme" },
    { key: "acompanhamento_aplicacao.espessura_camada.realizado", label: "Espessura Camada Realizado" },
    { key: "acompanhamento_aplicacao.espessura_camada.resultado", label: "Espessura Camada (cm)" },
    { key: "acompanhamento_aplicacao.espessura_camada.conforme", label: "Espessura Camada Conforme" },
    { key: "controle_aplicacao.km_estaca_inicial", label: "KM/Estaca Inicial" },
    { key: "controle_aplicacao.lado_inicial", label: "Lado Inicial" },
    { key: "controle_aplicacao.km_estaca_final", label: "KM/Estaca Final" },
    { key: "controle_aplicacao.lado_final", label: "Lado Final" },
    { key: "controle_aplicacao.quantidade_aplicada_m2", label: "Quantidade Aplicada (m²)" },
    { key: "acoes_corretivas_realizado", label: "Ações Corretivas" }
  ],
  ChecklistConcretagem: [
    { key: "data", label: "Data" },
    { key: "laboratorista_name", label: "Laboratorista" },
    { key: "rodovia", label: "Rodovia" },
    { key: "trecho", label: "Trecho" },
    { key: "concreteira", label: "Concreteira" },
    { key: "fck", label: "FCK (MPa)" },
    { key: "volume", label: "Volume (m³)" },
    { key: "cargas_concreto", label: "Cargas de Concreto", subfields: [
      { key: "numero_carga", label: "Nº Carga" },
      { key: "nota_fiscal", label: "Nota Fiscal" },
      { key: "slump_test.resultado", label: "Slump (cm)" },
      { key: "slump_test.conforme", label: "Slump Conforme" },
      { key: "espessura_camada.resultado", label: "Espessura (cm)" },
      { key: "espessura_camada.conforme", label: "Espessura Conforme" },
      { key: "superficie_tratada_limpa", label: "Superfície Tratada e Limpa" },
      { key: "adensamento_realizado", label: "Adensamento Realizado" },
      { key: "qtd_cps_3d", label: "Qtd CPs 3 dias" },
      { key: "tipo_ruptura_3d", label: "Tipo Ruptura 3 dias" },
      { key: "qtd_cps_7d", label: "Qtd CPs 7 dias" },
      { key: "tipo_ruptura_7d", label: "Tipo Ruptura 7 dias" },
      { key: "qtd_cps_28d", label: "Qtd CPs 28 dias" },
      { key: "tipo_ruptura_28d", label: "Tipo Ruptura 28 dias" }
    ]},
    { key: "acoes_corretivas_realizado", label: "Ações Corretivas" }
  ],
  ChecklistTerraplanagem: [
    { key: "laboratorista_name", label: "Laboratorista" },
    { key: "rodovia", label: "Rodovia" },
    { key: "empreiteira", label: "Empreiteira" },
    { key: "estaca", label: "Estaca" },
    { key: "camada", label: "Camada" },
    { key: "material", label: "Material" },
    { key: "acompanhamento_execucao.remocao_material_existente", label: "Remoção Material" },
    { key: "acompanhamento_execucao.espalhamento_material_novo", label: "Espalhamento Material" },
    { key: "acompanhamento_execucao.compactacao_conforme_projeto", label: "Compactação Conforme" },
    { key: "acompanhamento_execucao.ensaio_viga_benkelman", label: "Viga Benkelman" },
    { key: "acompanhamento_execucao.teste_carga", label: "Teste de Carga" },
    { key: "acompanhamento_execucao.falha_compactacao", label: "Falha Compactação" },
    { key: "ensaios_empreiteira.compactacao_proctor.quantidade", label: "Proctor - Qtde" },
    { key: "ensaios_empreiteira.compactacao_proctor.resultados", label: "Proctor - Resultados (g/cm³)" },
    { key: "ensaios_empreiteira.compactacao_proctor.conforme", label: "Proctor - Conforme" },
    { key: "umidade_otima_proctor", label: "Umidade Ótima (%)" },
    { key: "ensaios_empreiteira.isc.quantidade", label: "ISC - Qtde" },
    { key: "ensaios_empreiteira.isc.resultados", label: "ISC - Resultados (%)" },
    { key: "ensaios_empreiteira.isc.conforme", label: "ISC - Conforme" },
    { key: "ensaios_empreiteira.massa_especifica_in_situ.quantidade", label: "Massa Específica In Situ - Qtde" },
    { key: "ensaios_empreiteira.massa_especifica_in_situ.resultados", label: "Massa Específica In Situ - Resultados (g/cm³)" },
    { key: "ensaios_empreiteira.massa_especifica_in_situ.conforme", label: "Massa Específica In Situ - Conforme" },
    { key: "umidade_in_situ", label: "Umidade In Situ (%)" },
    { key: "ensaios_empreiteira.granulometria.quantidade", label: "Granulometria - Qtde" },
    { key: "ensaios_empreiteira.granulometria.conforme", label: "Granulometria - Conforme" },
    { key: "variacao_umidade_valor", label: "Variação Umidade (%)" },
    { key: "grau_compactacao_valor", label: "Grau Compactação (%)" },
    { key: "acoes_corretivas_realizado", label: "Ações Corretivas" }
  ],
  ChecklistReciclagem: [
    { key: "laboratorista_name", label: "Laboratorista" },
    { key: "rodovia", label: "Rodovia" },
    { key: "empreiteira", label: "Empreiteira" },
    { key: "estaca", label: "Estaca" },
    { key: "trecho", label: "Trecho" },
    { key: "faixa", label: "Faixa" },
    { key: "material", label: "Material" },
    { key: "inspetor_fiscal", label: "Inspetor Fiscal" },
    { key: "acompanhamento_execucao.remocao_material_existente", label: "Remoção Material" },
    { key: "acompanhamento_execucao.espalhamento_material_novo", label: "Espalhamento Material" },
    { key: "acompanhamento_execucao.compactacao_conforme_projeto", label: "Compactação Conforme" },
    { key: "acompanhamento_execucao.ensaio_viga_benkelman", label: "Viga Benkelman" },
    { key: "acompanhamento_execucao.teste_carga", label: "Teste de Carga" },
    { key: "acompanhamento_execucao.falha_compactacao", label: "Falha Compactação" },
    { key: "ensaios_empreiteira.compactacao_proctor.quantidade", label: "Proctor - Qtde" },
    { key: "ensaios_empreiteira.compactacao_proctor.resultados", label: "Proctor - Resultados (g/cm³)" },
    { key: "ensaios_empreiteira.compactacao_proctor.conforme", label: "Proctor - Conforme" },
    { key: "ensaios_empreiteira.taxa_agregado.quantidade", label: "Taxa Agregado - Qtde" },
    { key: "ensaios_empreiteira.taxa_agregado.resultados", label: "Taxa Agregado - Resultados" },
    { key: "ensaios_empreiteira.taxa_agregado.conforme", label: "Taxa Agregado - Conforme" },
    { key: "ensaios_empreiteira.taxa_cimento.quantidade", label: "Taxa Cimento - Qtde" },
    { key: "ensaios_empreiteira.taxa_cimento.resultados", label: "Taxa Cimento - Resultados" },
    { key: "ensaios_empreiteira.taxa_cimento.conforme", label: "Taxa Cimento - Conforme" },
    { key: "ensaios_empreiteira.umidade_frigideira.quantidade", label: "Umidade Frigideira - Qtde" },
    { key: "ensaios_empreiteira.umidade_frigideira.resultados", label: "Umidade Frigideira - Resultados (%)" },
    { key: "ensaios_empreiteira.umidade_frigideira.conforme", label: "Umidade Frigideira - Conforme" },
    { key: "ensaios_empreiteira.massa_especifica_in_situ.quantidade", label: "Massa Específica In Situ - Qtde" },
    { key: "ensaios_empreiteira.massa_especifica_in_situ.resultados", label: "Massa Específica In Situ - Resultados (g/cm³)" },
    { key: "ensaios_empreiteira.massa_especifica_in_situ.conforme", label: "Massa Específica In Situ - Conforme" },
    { key: "ensaios_empreiteira.granulometria.quantidade", label: "Granulometria - Qtde" },
    { key: "ensaios_empreiteira.granulometria.conforme", label: "Granulometria - Conforme" },
    { key: "ensaios_empreiteira.moldagem_resistencia.quantidade", label: "Moldagem Resistência - Qtde" },
    { key: "ensaios_empreiteira.moldagem_resistencia.conforme", label: "Moldagem Resistência - Conforme" },
    { key: "ensaios_empreiteira.viga_benkelman.quantidade", label: "Viga Benkelman - Qtde" },
    { key: "ensaios_empreiteira.viga_benkelman.conforme", label: "Viga Benkelman - Conforme" },
    { key: "ensaios_empreiteira.taxa_pintura_ligacao.quantidade", label: "Taxa Pintura Ligação - Qtde" },
    { key: "ensaios_empreiteira.taxa_pintura_ligacao.conforme", label: "Taxa Pintura Ligação - Conforme" },
    { key: "ensaios_empreiteira.finura_cimento.quantidade", label: "Finura Cimento - Qtde" },
    { key: "ensaios_empreiteira.finura_cimento.conforme", label: "Finura Cimento - Conforme" },
    { key: "acoes_corretivas_realizado", label: "Ações Corretivas" }
  ],
  EnsaioMRAF: [
    { key: "data_ensaio", label: "Data" },
    { key: "laboratorista_name", label: "Laboratorista" },
    { key: "placa_caminhao", label: "Placa Usina/Caminhão" },
    { key: "rodovia", label: "Rodovia" },
    { key: "trecho", label: "Trecho" },
    { key: "faixa_especificada", label: "Faixa" },
    { key: "tipo_ligante", label: "Tipo Ligante" },
    { key: "extracao_ligante.teor_ligante", label: "Teor Ligante (%)" },
    { key: "extracao_ligante.umidade", label: "Umidade (%)" },
    { key: "extracao_ligante.residuo_emulsao", label: "Resíduo da Emulsão (%)" },
    { key: "granulometria", label: "Granulometria (% passante)", subfields: [
      { key: "peneira_75_0mm", label: 'Nº 3"', astm: 'Nº 3"' },
      { key: "peneira_63_0mm", label: 'Nº 2½"', astm: 'Nº 2½"' },
      { key: "peneira_50_0mm", label: 'Nº 2"', astm: 'Nº 2"' },
      { key: "peneira_37_5mm", label: 'Nº 1½"', astm: 'Nº 1½"' },
      { key: "peneira_25_0mm", label: 'Nº 1"', astm: 'Nº 1"' },
      { key: "peneira_19_0mm", label: 'Nº ¾"', astm: 'Nº ¾"' },
      { key: "peneira_16_0mm", label: 'Nº ⅝"', astm: 'Nº ⅝"' },
      { key: "peneira_12_5mm", label: 'Nº ½"', astm: 'Nº ½"' },
      { key: "peneira_9_5mm", label: 'Nº ⅜"', astm: 'Nº ⅜"' },
      { key: "peneira_4_75mm", label: "Nº 4", astm: "Nº 4" },
      { key: "peneira_2_36mm", label: "Nº 8", astm: "Nº 8" },
      { key: "peneira_2_0mm", label: "Nº 10", astm: "Nº 10" },
      { key: "peneira_1_18mm", label: "Nº 16", astm: "Nº 16" },
      { key: "peneira_0_6mm", label: "Nº 30", astm: "Nº 30" },
      { key: "peneira_0_42mm", label: "Nº 40", astm: "Nº 40" },
      { key: "peneira_0_3mm", label: "Nº 50", astm: "Nº 50" },
      { key: "peneira_0_18mm", label: "Nº 80", astm: "Nº 80" },
      { key: "peneira_0_15mm", label: "Nº 100", astm: "Nº 100" },
      { key: "peneira_0_075mm", label: "Nº 200", astm: "Nº 200" }
    ]},
    { key: "approved", label: "Status Aprovação" }
  ],
  DiarioObra: [
    { key: "laboratorista_name", label: "Colaborador" },
    { key: "tipo_local", label: "Tipo Local" },
    { key: "rodovia", label: "Rodovia" },
    { key: "trecho", label: "Trecho" },
    { key: "condicoes_climaticas", label: "Condições Climáticas" },
    { key: "temperatura", label: "Temperatura (°C)" },
    { key: "acoes_corretivas_realizado", label: "Ações Corretivas" },
    { key: "acoes_corretivas_descricao", label: "Descrição Ações Corretivas" }
  ]
};