// Estado inicial do formulário de Checklist de Usina.
// Extraído de pages/ChecklistUsina/index.jsx para reduzir o tamanho da página.
import { todayISO } from "@/utils/formInitialData";

export const getInitialFormData = () => ({
  obra_id: "",
  project_id: "",
  data: todayISO(),
  jornada: { horario_inicio: "", horario_fim: "" },
  usina: "",
  projeto_utilizado: "",
  faixa_especificada: "",
  ligante: "",
  pedreira: "",
  inspetor_campo: "",
  ensaio_realizado_por: "Afirma Evias",
  controle_agregados: [],
  equivalente_areia_status: null,
  equivalente_areia_quantidade: 0,
  equivalente_areia_resultados: [],
  observacoes_agregados: "",
  rodadas_producao: [{
    numero_rodada: 1, horario_inicio: "", horario_termino: "",
    temperatura_ambiente: null, condicoes_climaticas: "bom",
    quantidade_produzida: null, controle_cargas_sim: false,
    controle_cargas_qtde: 0, caminhoes_enlonados: false,
    temperatura_massa_t1: null, temperatura_massa_t2: null,
  }],
  controle_cauq: {
    extracao_ligante_rotarex: { realizado: false, quantidade: 0, resultados: [], conforme: null },
    extracao_ligante_soxhlet: { realizado: false, quantidade: 0, resultados: [], conforme: null },
    granulometria: { realizado: false, quantidade: 0, resultados: [], conforme: null },
    densidade_rice: { realizado: false, quantidade: 0, resultados: [] },
    densidade_aparente: { realizado: false, quantidade: 0, resultados: [] },
    volume_vazios: { realizado: false, quantidade: 0, resultados: [], conforme: null },
    vam_marshall: { realizado: false, quantidade: 0, resultados: [], conforme: null },
    rbv: { realizado: false, quantidade: 0, resultados: [], conforme: null },
    rtcd_25c: { realizado: false, quantidade: 0, resultados: [], conforme: null },
    estabilidade: { realizado: false, quantidade: 0, resultados: [], conforme: null },
    fluencia: { realizado: false, quantidade: 0, resultados: [], conforme: null },
  },
  controle_ligante_ativo: false,
  controle_ligante: {
    nota_fiscal: "", fornecedor: "", placa_carreta: "", quantidade_toneladas: null,
    viscosidade_1_temp: "", viscosidade_1_sp: "", viscosidade_1_rpm: "", viscosidade_1_resultado: null, viscosidade_1_limite: "3000", viscosidade_1_conforme: false,
    viscosidade_2_temp: "", viscosidade_2_sp: "", viscosidade_2_rpm: "", viscosidade_2_resultado: null, viscosidade_2_limite: "2000", viscosidade_2_conforme: false,
    viscosidade_3_temp: "", viscosidade_3_sp: "", viscosidade_3_rpm: "", viscosidade_3_resultado: null, viscosidade_3_limite: "1000", viscosidade_3_conforme: false,
    recuperacao_elastica_resultado: null, recuperacao_elastica_limite: "75", recuperacao_elastica_conforme: false,
    penetracao_resultado: null, penetracao_limite: "45 a 70", penetracao_conforme: false,
    ponto_amolecimento_resultado: null, ponto_amolecimento_limite: "55", ponto_amolecimento_conforme: false,
    ponto_fulgor_resultado: null, ponto_fulgor_limite: "235", ponto_fulgor_conforme: false,
    observacoes: "",
  },
  observacoes: "",
  acoes_corretivas_realizado: null,
  acoes_corretivas_descricao: "",
  nao_conformidades: [],
  fotos: [],
  medicoes_usina: { sub_trecho: "", servico: "", cargas: [] },
  status: "rascunho",
  approved: null,
  rejection_reason: null,
});

export default getInitialFormData;